import { callBusinessData, loadTeacherData } from '../../services/teacher-data.js';

Page({
  data: { datasetId: '', classUuid: '', classes: [], students: [], exams: [], examUuid: '', subjects: [], examForm: { name: '', date: '', subjects: '语文,数学,英语' }, rows: [], analysis: null, trend: null, trendStudentIndex: 0, loading: false, saving: false, error: '', editingExam: false },
  onLoad(options) { const datasetId = options?.datasetId || wx.getStorageSync('activeDatasetId') || ''; this.setData({ datasetId }); if (!datasetId) { this.setData({ error: '请先导入或选择数据集' }); return; } this.loadBase(); },
  async loadBase() { this.setData({ loading: true, error: '' }); const [classes, students] = await Promise.all([loadTeacherData({ collectionName: 'classes', datasetId: this.data.datasetId }), loadTeacherData({ collectionName: 'students', datasetId: this.data.datasetId })]); if (!classes.ok || !students.ok) { this.setData({ loading: false, error: classes.error || students.error || '读取班级或学生失败' }); return; } const classUuid = classes.records[0]?.uuid || ''; const exams = await callBusinessData({ action: 'query', collection: 'exams', datasetId: this.data.datasetId, classUuid }); if (!exams?.ok) { this.setData({ loading: false, error: exams?.errors?.[0] || '读取考试失败' }); return; } this.setData({ loading: false, classes: classes.records, students: students.records, exams: exams.records || [], classUuid }); },
  selectClass(event) { const classUuid = this.data.classes[event.detail.value]?.uuid || ''; this.setData({ classUuid }); },
  selectExam(event) { const exam = this.data.exams[event.detail.value]; if (!exam) return; this.setData({ examUuid: exam.uuid, subjects: exam.subjects || [] }); this.loadScores(exam.uuid); },
  openExam() { this.setData({ editingExam: true, examForm: { name: '', date: new Date().toISOString().slice(0, 10), subjects: '语文,数学,英语' } }); },
  editExam() { const exam = this.data.exams.find((item) => item.uuid === this.data.examUuid); if (!exam) return; this.setData({ editingExam: true, examForm: { uuid: exam.uuid, name: exam.name || '', date: exam.date || '', subjects: (exam.subjects || []).join(',') } }); },
  onExamInput(event) { this.setData({ [`examForm.${event.currentTarget.dataset.field}`]: event.detail.value }); },
  async saveExam() { const form = this.data.examForm; if (!form.name.trim()) { wx.showToast({ title: '请输入考试名称', icon: 'none' }); return; } const payload = { name: form.name, date: form.date, subjects: form.subjects.split(',').map((item) => item.trim()).filter(Boolean) }; const result = form.uuid ? await callBusinessData({ action: 'update', collection: 'exams', datasetId: this.data.datasetId, uuid: form.uuid, record: payload }) : await callBusinessData({ action: 'create', collection: 'exams', datasetId: this.data.datasetId, classUuid: this.data.classUuid, record: payload }); if (!result?.ok) { this.setData({ error: result?.errors?.[0] || '保存考试失败' }); return; } this.setData({ editingExam: false }); this.loadBase(); },
  async deleteExam() { const exam = this.data.exams.find((item) => item.uuid === this.data.examUuid); if (!exam) return; const result = await callBusinessData({ action: 'delete', collection: 'exams', datasetId: this.data.datasetId, uuid: exam.uuid }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '删除考试失败', icon: 'none' }); this.setData({ examUuid: '', rows: [], analysis: null }); this.loadBase(); },
  async loadScores(examUuid) { const result = await callBusinessData({ action: 'query', collection: 'scores', datasetId: this.data.datasetId, classUuid: this.data.classUuid }); const saved = new Map((result?.records || []).filter((row) => row.examUuid === examUuid).map((row) => [`${row.studentUuid}:${row.subject}`, row.score])); const exam = this.data.exams.find((item) => item.uuid === examUuid); const subjects = exam?.subjects || []; this.setData({ rows: this.data.students.filter((student) => student.classUuid === this.data.classUuid).map((student) => ({ studentUuid: student.uuid, name: student.name, values: Object.fromEntries(subjects.map((subject) => [subject, saved.get(`${student.uuid}:${subject}`) ?? ''])) })) }); },
  onScoreInput(event) { const row = Number(event.currentTarget.dataset.row); const subject = event.currentTarget.dataset.subject; this.setData({ [`rows[${row}].values.${subject}`]: event.detail.value }); },
  async saveScores() { const exam = this.data.exams.find((item) => item.uuid === this.data.examUuid); if (!exam || !this.data.classUuid) return; const rows = this.data.rows.flatMap((row) => exam.subjects.map((subject) => ({ studentUuid: row.studentUuid, subject, score: row.values[subject] })).filter((item) => item.score !== '')); this.setData({ saving: true }); const result = await callBusinessData({ action: 'bulkSave', collection: 'scores', datasetId: this.data.datasetId, classUuid: this.data.classUuid, examUuid: exam.uuid, rows }); this.setData({ saving: false, error: result?.ok ? '' : (result?.errors?.[0] || '保存成绩失败') }); if (result?.ok) wx.showToast({ title: `已保存 ${result.count} 条`, icon: 'success' }); },
  async loadAnalysis() { if (!this.data.examUuid) return; const result = await callBusinessData({ action: 'analysis', collection: 'scores', datasetId: this.data.datasetId, classUuid: this.data.classUuid, examUuid: this.data.examUuid }); this.setData({ analysis: result?.ok ? result : null, error: result?.ok ? '' : (result?.errors?.[0] || '读取分析失败') }); },
  selectTrendStudent(event) { this.setData({ trendStudentIndex: Number(event.detail.value) }); },
  async loadTrend() { const student = this.data.students[this.data.trendStudentIndex]; if (!student || student.classUuid !== this.data.classUuid) return; const result = await callBusinessData({ action: 'trend', collection: 'scores', datasetId: this.data.datasetId, classUuid: this.data.classUuid, studentUuid: student.uuid }); this.setData({ trend: result?.ok ? result.points : null, error: result?.ok ? '' : (result?.errors?.[0] || '读取成绩走势失败') }); },
});
