import { callBusinessData, loadTeacherData } from '../../services/teacher-data.js';
import { buildScoreExchange, copyScoreExchange } from '../../services/score-export-service.js';
import { applyScoreImportRows, chooseScoreExchangeFile, exportScoreCsvFile, exportScoreXlsxFile, previewScoreExchangeFile } from '../../services/score-file-service.js';

Page({
  data: { datasetId: '', classUuid: '', classes: [], students: [], classStudents: [], exams: [], examUuid: '', subjects: [], examForm: { name: '', date: '', subjects: '语文,数学,英语' }, rows: [], analysis: null, trend: null, trendStudentIndex: 0, loading: false, saving: false, error: '', editingExam: false, importFileName: '', importPreview: null, importApplied: 0 },
  onLoad(options) { const datasetId = options?.datasetId || wx.getStorageSync('activeDatasetId') || ''; this.setData({ datasetId }); if (!datasetId) { this.setData({ error: '请先导入或选择数据集' }); return; } this.loadBase(); },
  async loadBase() { this.setData({ loading: true, error: '' }); const [classes, students] = await Promise.all([loadTeacherData({ collectionName: 'classes', datasetId: this.data.datasetId }), loadTeacherData({ collectionName: 'students', datasetId: this.data.datasetId })]); if (!classes.ok || !students.ok) { this.setData({ loading: false, error: classes.error || students.error || '读取班级或学生失败' }); return; } const classUuid = this.data.classUuid || classes.records[0]?.uuid || ''; const exams = await callBusinessData({ action: 'query', collection: 'exams', datasetId: this.data.datasetId, classUuid }); if (!exams?.ok) { this.setData({ loading: false, error: exams?.errors?.[0] || '读取考试失败' }); return; } this.setData({ loading: false, classes: classes.records, students: students.records, classStudents: students.records.filter((student) => student.classUuid === classUuid), exams: exams.records || [], classUuid }); },
  async selectClass(event) { const classUuid = this.data.classes[event.detail.value]?.uuid || ''; this.setData({ loading: true, classUuid, classStudents: this.data.students.filter((student) => student.classUuid === classUuid), examUuid: '', subjects: [], rows: [], analysis: null, trend: null, trendStudentIndex: 0, importFileName: '', importPreview: null, importApplied: 0 }); const exams = await callBusinessData({ action: 'query', collection: 'exams', datasetId: this.data.datasetId, classUuid }); this.setData({ loading: false, exams: exams?.ok ? (exams.records || []) : [], error: exams?.ok ? '' : (exams?.errors?.[0] || '读取考试失败') }); },
  selectExam(event) { const exam = this.data.exams[event.detail.value]; if (!exam) return; this.setData({ examUuid: exam.uuid, subjects: exam.subjects || [], importFileName: '', importPreview: null, importApplied: 0 }); this.loadScores(exam.uuid); },
  openExam() { this.setData({ editingExam: true, examForm: { name: '', date: new Date().toISOString().slice(0, 10), subjects: '语文,数学,英语' } }); },
  editExam() { const exam = this.data.exams.find((item) => item.uuid === this.data.examUuid); if (!exam) return; this.setData({ editingExam: true, examForm: { uuid: exam.uuid, name: exam.name || '', date: exam.date || '', subjects: (exam.subjects || []).join(',') } }); },
  onExamInput(event) { this.setData({ [`examForm.${event.currentTarget.dataset.field}`]: event.detail.value }); },
  async saveExam() { const form = this.data.examForm; if (!form.name.trim()) { wx.showToast({ title: '请输入考试名称', icon: 'none' }); return; } const payload = { name: form.name, date: form.date, subjects: form.subjects.split(',').map((item) => item.trim()).filter(Boolean) }; const result = form.uuid ? await callBusinessData({ action: 'update', collection: 'exams', datasetId: this.data.datasetId, uuid: form.uuid, record: payload }) : await callBusinessData({ action: 'create', collection: 'exams', datasetId: this.data.datasetId, classUuid: this.data.classUuid, record: payload }); if (!result?.ok) { this.setData({ error: result?.errors?.[0] || '保存考试失败' }); return; } this.setData({ editingExam: false }); this.loadBase(); },
  async deleteExam() { const exam = this.data.exams.find((item) => item.uuid === this.data.examUuid); if (!exam) return; const confirmed = await new Promise((resolve) => wx.showModal({ title: '删除考试', content: `确定删除“${exam.name || '该考试'}”及其成绩？`, success: (value) => resolve(value.confirm), fail: () => resolve(false) })); if (!confirmed) return; const result = await callBusinessData({ action: 'delete', collection: 'exams', datasetId: this.data.datasetId, uuid: exam.uuid }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '删除考试失败', icon: 'none' }); this.setData({ examUuid: '', rows: [], analysis: null }); this.loadBase(); },
  async loadScores(examUuid) { const result = await callBusinessData({ action: 'query', collection: 'scores', datasetId: this.data.datasetId, classUuid: this.data.classUuid }); const saved = new Map((result?.records || []).filter((row) => row.examUuid === examUuid).map((row) => [`${row.studentUuid}:${row.subject}`, row.score])); const exam = this.data.exams.find((item) => item.uuid === examUuid); const subjects = exam?.subjects || []; this.setData({ rows: this.data.students.filter((student) => student.classUuid === this.data.classUuid).map((student) => ({ studentUuid: student.uuid, name: student.name, schoolNo: student.schoolNo ?? student.school_no ?? '', values: Object.fromEntries(subjects.map((subject) => [subject, saved.get(`${student.uuid}:${subject}`) ?? ''])) })) }); },
  onScoreInput(event) { const row = Number(event.currentTarget.dataset.row); const subject = event.currentTarget.dataset.subject; this.setData({ [`rows[${row}].values.${subject}`]: event.detail.value }); },
  async chooseScoreFile() { if (!this.data.examUuid) return wx.showToast({ title: '请先选择考试', icon: 'none' }); this.setData({ loading: true, error: '', importPreview: null, importApplied: 0 }); try { const file = await chooseScoreExchangeFile(); const students = this.data.students.filter((student) => student.classUuid === this.data.classUuid); const preview = await previewScoreExchangeFile(file, { students, subjects: this.data.subjects }); this.setData({ loading: false, importFileName: file.name || '成绩文件', importPreview: preview }); } catch (error) { this.setData({ loading: false, error: error?.message || '读取成绩文件失败' }); } },
  cancelScoreImport() { this.setData({ importFileName: '', importPreview: null, importApplied: 0 }); },
  confirmScoreImport() { if (!this.data.importPreview?.rows?.length) return; const applied = applyScoreImportRows(this.data.rows, this.data.importPreview.rows); this.setData({ rows: applied.rows, importApplied: applied.applied }); wx.showToast({ title: `已填入 ${applied.applied} 条，请保存`, icon: 'none' }); },
  async exportScoreFile() { const exam = this.data.exams.find((item) => item.uuid === this.data.examUuid); if (!exam) return wx.showToast({ title: '请先选择考试', icon: 'none' }); try { await exportScoreCsvFile({ examName: exam.name, subjects: this.data.subjects, rows: this.data.rows }); } catch (error) { this.setData({ error: error?.errMsg || error?.message || '导出成绩文件失败' }); } },
  async exportScoreXlsxFile() { const exam = this.data.exams.find((item) => item.uuid === this.data.examUuid); if (!exam) return wx.showToast({ title: '请先选择考试', icon: 'none' }); try { await exportScoreXlsxFile({ examName: exam.name, subjects: this.data.subjects, rows: this.data.rows }); wx.showToast({ title: '成绩 Excel 已生成', icon: 'success' }); } catch (error) { this.setData({ error: error?.errMsg || error?.message || '导出成绩 Excel 失败' }); } },
  async saveScores() { const exam = this.data.exams.find((item) => item.uuid === this.data.examUuid); if (!exam || !this.data.classUuid) return; const rows = this.data.rows.flatMap((row) => exam.subjects.map((subject) => ({ studentUuid: row.studentUuid, subject, score: row.values[subject] })).filter((item) => item.score !== '')); this.setData({ saving: true }); const result = await callBusinessData({ action: 'bulkSave', collection: 'scores', datasetId: this.data.datasetId, classUuid: this.data.classUuid, examUuid: exam.uuid, rows }); this.setData({ saving: false, error: result?.ok ? '' : (result?.errors?.[0] || '保存成绩失败') }); if (result?.ok) wx.showToast({ title: `已保存 ${result.count} 条`, icon: 'success' }); },
  async loadAnalysis() { if (!this.data.examUuid) return; const result = await callBusinessData({ action: 'analysis', collection: 'scores', datasetId: this.data.datasetId, classUuid: this.data.classUuid, examUuid: this.data.examUuid }); this.setData({ analysis: result?.ok ? result : null, error: result?.ok ? '' : (result?.errors?.[0] || '读取分析失败') }); },
  copyExport() { const exam = this.data.exams.find((item) => item.uuid === this.data.examUuid); if (!exam) return; copyScoreExchange(buildScoreExchange({ exam, rows: this.data.rows, datasetId: this.data.datasetId, classUuid: this.data.classUuid })).then(() => wx.showToast({ title: '成绩 JSON 已复制', icon: 'success' })).catch(() => wx.showToast({ title: '复制导出失败', icon: 'none' })); },
  selectTrendStudent(event) { this.setData({ trendStudentIndex: Number(event.detail.value) }); },
  async loadTrend() { const student = this.data.classStudents[this.data.trendStudentIndex]; if (!student) return; const result = await callBusinessData({ action: 'trend', collection: 'scores', datasetId: this.data.datasetId, classUuid: this.data.classUuid, studentUuid: student.uuid }); this.setData({ trend: result?.ok ? result.points : null, error: result?.ok ? '' : (result?.errors?.[0] || '读取成绩走势失败') }); },
});
