import { callBusinessData, loadTeacherData } from '../../services/teacher-data.js';
import { buildDutyExchange, buildDutyRoster, copyDutyExchange, exportDutyCsvFile } from '../../services/duty-export-service.js';

const WEEK_NAMES = ['周一', '周二', '周三', '周四', '周五', '周六', '周日'];
Page({
  data: { datasetId: '', classUuid: '', classIndex: 0, classes: [], allStudents: [], students: [], groups: [], week: 1, groupCount: 4, selectedGroup: null, selectedDays: [], memberIndex: 0, newGroupNo: 1, renameGroupNo: 1, rosterWeeks: 8, rosterRows: [], loading: false, saving: false, error: '', weekNames: WEEK_NAMES },
  onLoad(options) { const datasetId = options?.datasetId || wx.getStorageSync('activeDatasetId') || ''; this.setData({ datasetId }); if (!datasetId) { this.setData({ error: '请先导入或选择数据集' }); return; } this.loadBase(); },
  async loadBase() { this.setData({ loading: true, error: '' }); const [classes, students] = await Promise.all([loadTeacherData({ collectionName: 'classes', datasetId: this.data.datasetId }), loadTeacherData({ collectionName: 'students', datasetId: this.data.datasetId })]); if (!classes.ok || !students.ok) return this.setData({ loading: false, error: classes.error || students.error }); const cls = classes.records[0]; if (!cls) return this.setData({ loading: false, error: '请先创建班级' }); this.setData({ loading: false, classes: classes.records, classIndex: 0, classUuid: cls.uuid, allStudents: students.records, students: students.records.filter((item) => item.classUuid === cls.uuid && item.status !== '离校') }); this.loadDuties(); },
  async loadDuties() { const classUuid = this.data.classUuid; const result = await callBusinessData({ action: 'query', collection: 'duties', datasetId: this.data.datasetId, classUuid }); if (classUuid !== this.data.classUuid) return; const names = new Map(this.data.students.map((item) => [item.uuid, item.name || '未命名学生'])); const map = new Map(); for (const row of result?.records || []) { if (row.role !== '值日生') continue; const no = Number(row.groupNo || 1); if (!map.has(no)) map.set(no, { no, members: [], groupDays: row.groupDays || '' }); map.get(no).members.push({ ...row, studentName: names.get(row.studentUuid) || '未命名学生' }); } const groups = [...map.values()].sort((a, b) => a.no - b.no); const nextNo = groups.length ? Math.min(20, Math.max(...groups.map((item) => item.no)) + 1) : 1; this.setData({ groups, rosterRows: buildDutyRoster(groups, this.data.rosterWeeks), newGroupNo: nextNo, error: result?.ok ? '' : (result?.errors?.[0] || '读取值日数据失败') }); },
  selectClass(event) { const classIndex = Number(event.detail.value); const cls = this.data.classes[classIndex]; if (!cls) return; this.setData({ classIndex, classUuid: cls.uuid, students: this.data.allStudents.filter((item) => item.classUuid === cls.uuid && item.status !== '离校'), selectedGroup: null }); this.loadDuties(); },
  openGroup(event) { const group = this.data.groups[Number(event.currentTarget.dataset.index)]; if (!group) return; this.setData({ selectedGroup: group.no, renameGroupNo: group.no, selectedDays: group.groupDays ? group.groupDays.split(',').filter(Boolean) : [] }); },
  toggleDay(event) { const day = String(event.currentTarget.dataset.day); const days = this.data.selectedDays.includes(day) ? this.data.selectedDays.filter((item) => item !== day) : [...this.data.selectedDays, day].sort(); this.setData({ selectedDays: days }); },
  async saveDays() { if (!this.data.selectedGroup) return; this.setData({ saving: true }); const result = await callBusinessData({ action: 'groupDays', collection: 'duties', datasetId: this.data.datasetId, classUuid: this.data.classUuid, groupNo: this.data.selectedGroup, groupDays: this.data.selectedDays.join(',') }); this.setData({ saving: false }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '保存失败', icon: 'none' }); wx.showToast({ title: '值日星期已保存', icon: 'success' }); this.loadDuties(); },
  onMemberPicker(event) { this.setData({ memberIndex: Number(event.detail.value) }); },
  onGroupNumber(event) { const field = event.currentTarget.dataset.field; this.setData({ [field]: Math.max(1, Math.min(20, Number(event.detail.value) || 1)) }); },
  startNewGroup() { const no = this.data.newGroupNo; if (this.data.groups.some((item) => item.no === no)) return wx.showToast({ title: '该组号已存在', icon: 'none' }); this.setData({ selectedGroup: no, renameGroupNo: no, selectedDays: [] }); wx.showToast({ title: '请选择首位组员', icon: 'none' }); },
  async addMember() { const group = this.data.groups.find((item) => item.no === this.data.selectedGroup) || { no: this.data.selectedGroup, members: [], groupDays: '' }; const student = this.data.students[this.data.memberIndex]; if (!group.no || !student) return; if (group.members.some((row) => row.studentUuid === student.uuid)) return wx.showToast({ title: '该学生已在本组', icon: 'none' }); if (this.data.groups.some((item) => item.members.some((row) => row.studentUuid === student.uuid))) return wx.showToast({ title: '每名学生只能在一个值日组', icon: 'none' }); const result = await callBusinessData({ action: 'create', collection: 'duties', datasetId: this.data.datasetId, classUuid: this.data.classUuid, record: { studentUuid: student.uuid, role: '值日生', groupNo: group.no, groupDays: group.groupDays || '', remark: '' } }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '加人失败', icon: 'none' }); wx.showToast({ title: '已加入值日组', icon: 'success' }); this.loadDuties(); },
  async removeMember(event) { const group = this.data.groups.find((item) => item.no === this.data.selectedGroup); const row = group?.members[Number(event.currentTarget.dataset.index)]; if (!row?.uuid) return; const result = await callBusinessData({ action: 'delete', collection: 'duties', datasetId: this.data.datasetId, uuid: row.uuid }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '移除失败', icon: 'none' }); this.loadDuties(); },
  async renameGroup() { const from = this.data.selectedGroup; const to = this.data.renameGroupNo; if (!from || from === to) return; const result = await callBusinessData({ action: 'renameDutyGroup', collection: 'duties', datasetId: this.data.datasetId, classUuid: this.data.classUuid, groupNo: from, targetGroupNo: to }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '修改组号失败', icon: 'none' }); this.setData({ selectedGroup: to }); this.loadDuties(); },
  deleteGroup() { const groupNo = this.data.selectedGroup; if (!groupNo) return; wx.showModal({ title: '删除整组', content: `将移除第 ${groupNo} 组的全部值日成员，确认继续吗？`, confirmColor: '#d64541', success: async (modal) => { if (!modal.confirm) return; const result = await callBusinessData({ action: 'deleteDutyGroup', collection: 'duties', datasetId: this.data.datasetId, classUuid: this.data.classUuid, groupNo }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '删除组失败', icon: 'none' }); this.setData({ selectedGroup: null }); this.loadDuties(); } }); },
  copyExport() { copyDutyExchange(buildDutyExchange(this.data.groups, { datasetId: this.data.datasetId, classUuid: this.data.classUuid })).then(() => wx.showToast({ title: '值日 JSON 已复制', icon: 'success' })).catch(() => wx.showToast({ title: '复制导出失败', icon: 'none' })); },
  async exportRosterCsv() { const cls = this.data.classes.find((item) => item.uuid === this.data.classUuid) || {}; try { await exportDutyCsvFile(this.data.groups, { className: cls.name || '班级', weeks: this.data.rosterWeeks }); } catch (error) { wx.showToast({ title: error?.message || '导出失败', icon: 'none' }); } },
  onRosterWeeks(event) { const rosterWeeks = Math.max(1, Math.min(52, Number(event.detail.value) || this.data.groups.length || 1)); this.setData({ rosterWeeks, rosterRows: buildDutyRoster(this.data.groups, rosterWeeks) }); },
  onGroupCountInput(event) { this.setData({ groupCount: Math.max(1, Math.min(15, Number(event.detail.value) || 1)) }); },
  async autoGroup() { if (!this.data.classUuid) return; this.setData({ saving: true }); const result = await callBusinessData({ action: 'autoGroup', collection: 'duties', datasetId: this.data.datasetId, classUuid: this.data.classUuid, groupCount: this.data.groupCount }); this.setData({ saving: false }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '自动分组失败', icon: 'none' }); wx.showToast({ title: `已生成 ${result.groupCount} 组`, icon: 'success' }); this.loadDuties(); },
  async preset(event) { const action = event.currentTarget.dataset.action; this.setData({ saving: true }); const result = await callBusinessData({ action, collection: 'duties', datasetId: this.data.datasetId, classUuid: this.data.classUuid }); this.setData({ saving: false }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '预设失败', icon: 'none' }); wx.showToast({ title: `已补齐 ${result.added?.length || 0} 项`, icon: 'success' }); this.loadDuties(); },
  onWeekInput(event) { this.setData({ week: Math.max(1, Number(event.detail.value) || 1) }); },
});
