import { callBusinessData, loadTeacherData } from '../../services/teacher-data.js';

const WEEK_NAMES = ['周一', '周二', '周三', '周四', '周五', '周六', '周日'];
Page({
  data: { datasetId: '', classUuid: '', classes: [], students: [], groups: [], week: 1, groupCount: 4, selectedGroup: null, selectedDays: [], loading: false, saving: false, error: '', weekNames: WEEK_NAMES },
  onLoad(options) { const datasetId = options?.datasetId || wx.getStorageSync('activeDatasetId') || ''; this.setData({ datasetId }); if (!datasetId) { this.setData({ error: '请先导入或选择数据集' }); return; } this.loadBase(); },
  async loadBase() { this.setData({ loading: true, error: '' }); const [classes, students] = await Promise.all([loadTeacherData({ collectionName: 'classes', datasetId: this.data.datasetId }), loadTeacherData({ collectionName: 'students', datasetId: this.data.datasetId })]); if (!classes.ok || !students.ok) { this.setData({ loading: false, error: classes.error || students.error }); return; } const cls = classes.records[0] || {}; this.setData({ loading: false, classes: classes.records, classUuid: cls.uuid, students: students.records.filter((item) => item.classUuid === cls.uuid && item.status !== '离校') }); this.loadDuties(); },
  async loadDuties() { const result = await callBusinessData({ action: 'query', collection: 'duties', datasetId: this.data.datasetId, classUuid: this.data.classUuid }); const map = new Map(); for (const row of result?.records || []) { const no = Number(row.groupNo || 1); if (!map.has(no)) map.set(no, { no, members: [], groupDays: row.groupDays || '' }); map.get(no).members.push(row); } this.setData({ groups: [...map.values()].sort((a, b) => a.no - b.no), error: result?.ok ? '' : (result?.errors?.[0] || '读取值日数据失败') }); },
  selectClass(event) { const cls = this.data.classes[event.detail.value]; if (!cls) return; this.setData({ classUuid: cls.uuid, students: this.data.students.filter((item) => item.classUuid === cls.uuid), selectedGroup: null }); this.loadDuties(); },
  studentName(uuid) { return this.data.students.find((item) => item.uuid === uuid)?.name || '未命名学生'; },
  openGroup(event) { const group = this.data.groups[Number(event.currentTarget.dataset.index)]; if (!group) return; this.setData({ selectedGroup: group.no, selectedDays: group.groupDays ? group.groupDays.split(',').filter(Boolean) : [] }); },
  toggleDay(event) { const day = String(event.currentTarget.dataset.day); const days = this.data.selectedDays.includes(day) ? this.data.selectedDays.filter((item) => item !== day) : [...this.data.selectedDays, day].sort(); this.setData({ selectedDays: days }); },
  async saveDays() { if (!this.data.selectedGroup) return; this.setData({ saving: true }); const result = await callBusinessData({ action: 'groupDays', collection: 'duties', datasetId: this.data.datasetId, classUuid: this.data.classUuid, groupNo: this.data.selectedGroup, groupDays: this.data.selectedDays.join(',') }); this.setData({ saving: false }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '保存失败', icon: 'none' }); wx.showToast({ title: '值日星期已保存', icon: 'success' }); this.loadDuties(); },
  onGroupCountInput(event) { this.setData({ groupCount: Math.max(1, Math.min(15, Number(event.detail.value) || 1)) }); },
  async autoGroup() { if (!this.data.classUuid) return; this.setData({ saving: true }); const result = await callBusinessData({ action: 'autoGroup', collection: 'duties', datasetId: this.data.datasetId, classUuid: this.data.classUuid, groupCount: this.data.groupCount }); this.setData({ saving: false }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '自动分组失败', icon: 'none' }); wx.showToast({ title: `已生成 ${result.groupCount} 组`, icon: 'success' }); this.loadDuties(); },
  async preset(event) { const action = event.currentTarget.dataset.action; this.setData({ saving: true }); const result = await callBusinessData({ action, collection: 'duties', datasetId: this.data.datasetId, classUuid: this.data.classUuid }); this.setData({ saving: false }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '预设失败', icon: 'none' }); wx.showToast({ title: `已补齐 ${result.added?.length || 0} 项`, icon: 'success' }); this.loadDuties(); },
  onWeekInput(event) { this.setData({ week: Math.max(1, Number(event.detail.value) || 1) }); },
});
