import { callBusinessData, loadTeacherData } from '../../services/teacher-data.js';

const METHODS = ['家访', '电话', '微信', '到校面谈', '其他'];
Page({
  data: { datasetId: '', classUuid: '', studentUuid: '', classes: [], students: [], records: [], methods: METHODS, month: '', studentIndex: -1, methodIndex: 0, form: {}, editing: false, loading: false, saving: false, error: '', stats: { total: 0, students: 0, visits: 0, phones: 0 } },
  onLoad(options) { const datasetId = options?.datasetId || wx.getStorageSync('activeDatasetId') || ''; this.setData({ datasetId, classUuid: options?.classUuid || '', studentUuid: options?.studentUuid || '' }); if (!datasetId) { this.setData({ error: '请先导入或选择数据集' }); return; } this.loadBase(); },
  async loadBase() { this.setData({ loading: true }); const [classes, students] = await Promise.all([loadTeacherData({ collectionName: 'classes', datasetId: this.data.datasetId }), loadTeacherData({ collectionName: 'students', datasetId: this.data.datasetId })]); if (!classes.ok || !students.ok) return this.setData({ loading: false, error: classes.error || students.error }); const classUuid = this.data.classUuid || classes.records[0]?.uuid || ''; this.setData({ classes: classes.records, classUuid, students: students.records.filter((item) => item.classUuid === classUuid && item.status !== '离校'), loading: false }); this.load(); },
  async load() { const [list, stats] = await Promise.all([callBusinessData({ action: 'query', collection: 'contacts', datasetId: this.data.datasetId, classUuid: this.data.classUuid, studentUuid: this.data.studentUuid }), callBusinessData({ action: 'contactStats', collection: 'contacts', datasetId: this.data.datasetId, classUuid: this.data.classUuid, month: this.data.month })]); this.setData({ records: list?.records || [], stats: stats?.ok ? stats : this.data.stats, error: list?.ok ? '' : (list?.errors?.[0] || '读取沟通记录失败') }); },
  selectClass(event) { const cls = this.data.classes[event.detail.value]; if (!cls) return; this.setData({ classUuid: cls.uuid, students: this.data.students.filter((item) => item.classUuid === cls.uuid) }); this.load(); },
  onMonthInput(event) { this.setData({ month: event.detail.value }); this.load(); },
  openCreate() { this.setData({ editing: true, form: { date: new Date().toISOString().slice(0, 10), studentUuid: this.data.studentUuid || '', method: METHODS[0], topic: '', result: '', remark: '' }, studentIndex: Math.max(-1, this.data.students.findIndex((item) => item.uuid === this.data.studentUuid)), methodIndex: 0 }); },
  openEdit(event) { const row = this.data.records[Number(event.currentTarget.dataset.index)]; if (!row) return; this.setData({ editing: true, form: { ...row }, studentIndex: Math.max(0, this.data.students.findIndex((item) => item.uuid === row.studentUuid)), methodIndex: Math.max(0, METHODS.indexOf(row.method)) }); },
  selectStudent(event) { const index = Number(event.detail.value); this.setData({ studentIndex: index, 'form.studentUuid': this.data.students[index]?.uuid || '' }); },
  selectMethod(event) { const index = Number(event.detail.value); this.setData({ methodIndex: index, 'form.method': METHODS[index] }); },
  onInput(event) { this.setData({ [`form.${event.currentTarget.dataset.field}`]: event.detail.value }); },
  cancel() { this.setData({ editing: false }); },
  async save() { if (!this.data.form.studentUuid) return wx.showToast({ title: '请选择学生', icon: 'none' }); if (!this.data.form.date) return wx.showToast({ title: '请填写日期', icon: 'none' }); this.setData({ saving: true }); const input = { collection: 'contacts', datasetId: this.data.datasetId, classUuid: this.data.classUuid, record: this.data.form }; const result = this.data.form.uuid ? await callBusinessData({ ...input, action: 'update', uuid: this.data.form.uuid }) : await callBusinessData({ ...input, action: 'create' }); this.setData({ saving: false }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '保存失败', icon: 'none' }); this.setData({ editing: false }); wx.showToast({ title: '已保存', icon: 'success' }); this.load(); },
  remove(event) { const row = this.data.records[Number(event.currentTarget.dataset.index)]; if (!row) return; wx.showModal({ title: '删除沟通记录', content: '删除后将无法在当前列表中查看，确认继续吗？', success: async (choice) => { if (!choice.confirm) return; const result = await callBusinessData({ action: 'delete', collection: 'contacts', datasetId: this.data.datasetId, classUuid: this.data.classUuid, uuid: row.uuid }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '删除失败', icon: 'none' }); wx.showToast({ title: '已删除', icon: 'success' }); this.load(); } }); },
  studentName(uuid) { return this.data.students.find((item) => item.uuid === uuid)?.name || '未知学生'; },
});
