import { callBusinessData, loadTeacherData } from '../../services/teacher-data.js';
Page({
  data: { datasetId: '', classUuid: '', classes: [], students: [], records: [], month: '', form: { date: '', studentUuid: '', categoryName: '', itemName: '', score: '', remark: '' }, studentIndex: -1, editing: false, saving: false, loading: false, error: '', history: [], historyVisible: false, summary: { positive: 0, negative: 0, net: 0, count: 0 } },
  onLoad(options) { const datasetId = options?.datasetId || wx.getStorageSync('activeDatasetId') || ''; this.setData({ datasetId, 'form.date': new Date().toISOString().slice(0, 10) }); if (!datasetId) return this.setData({ error: '请先导入或选择数据集' }); this.loadBase(); },
  async loadBase() { const [classes, students] = await Promise.all([loadTeacherData({ collectionName: 'classes', datasetId: this.data.datasetId }), loadTeacherData({ collectionName: 'students', datasetId: this.data.datasetId })]); if (!classes.ok || !students.ok) return this.setData({ error: classes.error || students.error }); const cls = classes.records[0] || {}; this.setData({ classes: classes.records, classUuid: cls.uuid, students: students.records.filter((item) => item.classUuid === cls.uuid && item.status !== '离校') }); this.load(); },
  async load() { const result = await callBusinessData({ action: 'query', collection: 'assessment_records', datasetId: this.data.datasetId, classUuid: this.data.classUuid }); let records = result?.records || []; if (this.data.month) records = records.filter((item) => String(item.date || item.behaviorDate || '').startsWith(this.data.month)); const positive = records.filter((item) => Number(item.score || 0) > 0).reduce((sum, item) => sum + Number(item.score), 0); const negative = records.filter((item) => Number(item.score || 0) < 0).reduce((sum, item) => sum + Number(item.score), 0); this.setData({ records, summary: { positive, negative, net: positive + negative, count: records.length }, error: result?.ok ? '' : (result?.errors?.[0] || '读取表现记录失败') }); },
  selectClass(event) { const cls = this.data.classes[event.detail.value]; if (!cls) return; this.setData({ classUuid: cls.uuid, students: this.data.students.filter((item) => item.classUuid === cls.uuid) }); this.load(); },
  onMonthInput(event) { this.setData({ month: event.detail.value }); this.load(); },
  openCreate() { this.setData({ editing: true, studentIndex: -1, form: { date: new Date().toISOString().slice(0, 10), studentUuid: '', categoryName: '', itemName: '', score: '', remark: '' } }); },
  openEdit(event) { const row = this.data.records[Number(event.currentTarget.dataset.index)]; if (row) this.setData({ editing: true, form: { ...row, date: row.date || row.behaviorDate || '' }, studentIndex: this.data.students.findIndex((item) => item.uuid === row.studentUuid) }); },
  selectStudent(event) { const index = Number(event.detail.value); this.setData({ studentIndex: index, 'form.studentUuid': this.data.students[index]?.uuid || '' }); },
  onInput(event) { this.setData({ [`form.${event.currentTarget.dataset.field}`]: event.detail.value }); },
  cancel() { this.setData({ editing: false }); },
  async save() { const score = Number(this.data.form.score); if (!this.data.form.studentUuid || !this.data.form.itemName || !Number.isFinite(score)) return wx.showToast({ title: '请完整填写学生、行为和分值', icon: 'none' }); this.setData({ saving: true }); const input = { collection: 'assessment_records', datasetId: this.data.datasetId, classUuid: this.data.classUuid, record: { ...this.data.form, score } }; const result = this.data.form.uuid ? await callBusinessData({ ...input, action: 'update', uuid: this.data.form.uuid }) : await callBusinessData({ ...input, action: 'create' }); this.setData({ saving: false }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '保存失败', icon: 'none' }); this.setData({ editing: false }); wx.showToast({ title: '记分已保存', icon: 'success' }); this.load(); },
  async remove(event) { const row = this.data.records[Number(event.currentTarget.dataset.index)]; if (!row) return; const result = await callBusinessData({ action: 'delete', collection: 'assessment_records', datasetId: this.data.datasetId, uuid: row.uuid }); if (!result?.ok) return wx.showToast({ title: result?.errors?.[0] || '撤销失败', icon: 'none' }); wx.showToast({ title: '记录已撤销', icon: 'success' }); this.load(); },
  async showHistory(event) { const row = this.data.records[Number(event.currentTarget.dataset.index)]; if (!row) return; const result = await callBusinessData({ action: 'history', collection: 'assessment_revisions', datasetId: this.data.datasetId, recordUuid: row.uuid }); this.setData({ history: result?.records || [], historyVisible: true }); },
  openRules() { wx.navigateTo({ url: `/pages/assessment-rules/index?datasetId=${encodeURIComponent(this.data.datasetId)}` }); },
  studentName(uuid) { return this.data.students.find((item) => item.uuid === uuid)?.name || '未知学生'; },
});
