import { callBusinessData, loadTeacherData } from '../../services/teacher-data.js';

Page({
  data: { datasetId: '', classUuid: '', classes: [], students: [], rows: 6, cols: 8, grid: [], selected: null, loading: false, saving: false, error: '', historyVisible: false, history: [], autoOpts: { nearVision: true, gender: false, peerHelp: false }, autoConflicts: [] },
  onLoad(options) { const datasetId = options?.datasetId || wx.getStorageSync('activeDatasetId') || ''; this.setData({ datasetId }); if (!datasetId) { this.setData({ error: '请先导入或选择数据集' }); return; } this.loadBase(); },
  async loadBase() { this.setData({ loading: true, error: '' }); const [classes, students] = await Promise.all([loadTeacherData({ collectionName: 'classes', datasetId: this.data.datasetId }), loadTeacherData({ collectionName: 'students', datasetId: this.data.datasetId })]); if (!classes.ok || !students.ok) { this.setData({ loading: false, error: classes.error || students.error }); return; } const cls = classes.records[0] || {}; this.setData({ loading: false, classes: classes.records, students: students.records.filter((item) => item.classUuid === cls.uuid), classUuid: cls.uuid, rows: Number(cls.seatRows || cls.seat_rows || 6), cols: Number(cls.seatCols || cls.seat_cols || 8) }); this.loadSeats(cls.uuid); },
  async loadSeats(classUuid = this.data.classUuid) { const result = await callBusinessData({ action: 'query', collection: 'seats', datasetId: this.data.datasetId, classUuid }); const saved = new Map((result?.records || []).map((item) => [`${item.row}:${item.col}`, item])); const grid = []; for (let row = 0; row < this.data.rows; row += 1) for (let col = 0; col < this.data.cols; col += 1) grid.push(saved.get(`${row}:${col}`) || { row, col, studentUuid: '', locked: false }); this.setData({ grid, error: result?.ok ? '' : (result?.errors?.[0] || '读取座位失败') }); },
  selectClass(event) { const cls = this.data.classes[event.detail.value]; if (!cls) return; this.setData({ classUuid: cls.uuid, rows: Number(cls.seatRows || cls.seat_rows || 6), cols: Number(cls.seatCols || cls.seat_cols || 8), students: this.data.students.filter((item) => item.classUuid === cls.uuid) }); this.loadSeats(cls.uuid); },
  studentName(uuid) { return this.data.students.find((item) => item.uuid === uuid)?.name || '空座'; },
  selectSeat(event) { const index = Number(event.currentTarget.dataset.index); this.setData({ selected: index }); },
  chooseStudent(event) { const index = Number(event.detail.value); const studentUuid = this.data.students[index]?.uuid || ''; if (this.data.selected === null) return; this.setData({ [`grid[${this.data.selected}].studentUuid`]: studentUuid }); },
  toggleLock() { if (this.data.selected === null) return; this.setData({ [`grid[${this.data.selected}].locked`]: !this.data.grid[this.data.selected].locked }); },
  clearSeat() { if (this.data.selected === null) return; this.setData({ [`grid[${this.data.selected}].studentUuid`]: '' }); },
  toggleAutoOption(event) { const key = event.currentTarget.dataset.key; if (!key) return; this.setData({ [`autoOpts.${key}`]: Boolean(event.detail.value) }); },
  autoArrange() { const byUuid = new Map(this.data.students.map((student) => [student.uuid, student])); const lockedUuids = new Set(this.data.grid.filter((item) => item.locked && item.studentUuid).map((item) => item.studentUuid)); const ordered = this.data.students.filter((student) => !lockedUuids.has(student.uuid)).sort((a, b) => { const av = Number(a.heightCm ?? a.height_cm ?? 0); const bv = Number(b.heightCm ?? b.height_cm ?? 0); const ap = /近视|远视|散光|poor|myopia/i.test(String(a.vision || '')); const bp = /近视|远视|散光|poor|myopia/i.test(String(b.vision || '')); return (av || 0) - (bv || 0) || Number(bp) - Number(ap); }); const next = this.data.grid.map((item) => item.locked ? { ...item } : ({ ...item, studentUuid: '' })); const center = (this.data.cols - 1) / 2; let assigned = 0; for (const student of ordered) { const poorVision = /近视|远视|散光|poor|myopia/i.test(String(student.vision || '')); const candidates = next.filter((item) => !item.locked && !item.studentUuid).sort((a, b) => { const ac = Math.abs(a.col - center); const bc = Math.abs(b.col - center); if (this.data.autoOpts.nearVision && poorVision && ac !== bc) return ac - bc; return a.row - b.row || ac - bc; }); if (!candidates[0]) break; candidates[0].studentUuid = student.uuid; assigned += 1; } const conflicts = []; if (this.data.autoOpts.gender) { const byRow = new Map(); next.filter((item) => item.studentUuid).forEach((item) => { const student = byUuid.get(item.studentUuid); if (!byRow.has(item.row)) byRow.set(item.row, []); byRow.get(item.row).push({ item, student }); }); byRow.forEach((items, row) => { items.sort((a, b) => a.item.col - b.item.col); for (let i = 1; i < items.length; i += 1) if (items[i].student && items[i - 1].student && items[i].student.gender === items[i - 1].student.gender) conflicts.push(`第 ${row + 1} 排存在同性相邻`); }); } if (this.data.autoOpts.peerHelp) conflicts.push('成绩互助请在座位图中确认相邻学生搭配'); const unplaced = ordered.length - assigned; this.setData({ grid: next, autoConflicts: conflicts }); wx.showToast({ title: unplaced ? `还有 ${unplaced} 人未入座` : '自动排座完成', icon: unplaced ? 'none' : 'success' }); },
  shift(event) { const dr = Number(event.currentTarget.dataset.dr) || 0; const dc = Number(event.currentTarget.dataset.dc) || 0; const movable = this.data.grid.filter((item) => item.studentUuid && !item.locked); const next = this.data.grid.map((item) => item.locked ? { ...item } : ({ ...item, studentUuid: '' })); for (const item of movable) { const row = (item.row + dr + this.data.rows) % this.data.rows; const col = (item.col + dc + this.data.cols) % this.data.cols; const target = next.find((seat) => seat.row === row && seat.col === col); const fallback = next.find((seat) => !seat.locked && !seat.studentUuid); if (target && !target.locked && !target.studentUuid) target.studentUuid = item.studentUuid; else if (fallback) fallback.studentUuid = item.studentUuid; } this.setData({ grid: next }); },
  async showHistory() { const result = await callBusinessData({ action: 'layoutHistory', collection: 'seat_layouts', datasetId: this.data.datasetId, classUuid: this.data.classUuid }); this.setData({ history: result?.records || [], historyVisible: true, error: result?.ok ? '' : (result?.errors?.[0] || '读取历史布局失败') }); },
  restoreHistory(event) { const row = this.data.history[Number(event.currentTarget.dataset.index)]; if (!row?.grid) return; this.setData({ grid: row.grid.map((item) => ({ ...item })), historyVisible: false }); wx.showToast({ title: '已载入历史布局', icon: 'success' }); },
  async save() { this.setData({ saving: true, error: '' }); const existing = await callBusinessData({ action: 'query', collection: 'seats', datasetId: this.data.datasetId, classUuid: this.data.classUuid }); for (const item of existing?.records || []) await callBusinessData({ action: 'delete', collection: 'seats', datasetId: this.data.datasetId, classUuid: this.data.classUuid, uuid: item.uuid }); let count = 0; for (const item of this.data.grid) if (item.studentUuid || item.locked) { const result = await callBusinessData({ action: 'create', collection: 'seats', datasetId: this.data.datasetId, classUuid: this.data.classUuid, record: item }); if (result?.ok) count += 1; } const snapshot = await callBusinessData({ action: 'layoutSave', collection: 'seat_layouts', datasetId: this.data.datasetId, classUuid: this.data.classUuid, layout: { rows: this.data.rows, cols: this.data.cols, grid: this.data.grid.map((item) => ({ ...item })) } }); this.setData({ saving: false, error: snapshot?.ok ? '' : (snapshot?.errors?.[0] || '布局历史保存失败') }); wx.showToast({ title: `已保存 ${count} 个座位`, icon: 'success' }); this.loadSeats(); },
});
