import { callBusinessData, callClassData, loadTeacherData } from '../../services/teacher-data.js';
import { arrangeStudents, hasAisleBefore, resizeGrid } from '../../services/seat-layout-service.js';

const aisleLabels = ['均分', '中间走道', '双走道'];
const classRows = (cls = {}) => Number(cls.seatRows ?? cls.seat_rows ?? 6);
const classCols = (cls = {}) => Number(cls.seatCols ?? cls.seat_cols ?? 8);
const classAisle = (cls = {}) => Number(cls.aisleMode ?? cls.aisle_mode ?? 1);
function cleanGrid(grid) { return grid.map(({ row, col, studentUuid, locked }) => ({ row, col, studentUuid: String(studentUuid || ''), locked: locked === true })); }
function decorateGrid(grid, students, cols, aisleMode) { const byUuid = new Map(students.map((student) => [student.uuid, student])); return grid.map((seat) => { const student = byUuid.get(seat.studentUuid); return { ...seat, displayName: student?.name || '空座', seatNote: String(student?.seatNote ?? student?.seat_note ?? ''), aisleBefore: hasAisleBefore(seat.col, cols, aisleMode) }; }); }

Page({
  data: { datasetId: '', classUuid: '', classIndex: 0, classes: [], allStudents: [], students: [], rows: 6, cols: 8, aisleMode: 1, aisleLabels, podiumLabel: '讲台', layoutRemark: '', grid: [], selected: null, selectedStudentName: '', selectedSeatNote: '', loading: false, saving: false, error: '', historyVisible: false, history: [], autoOpts: { nearVision: true, gender: false, peerHelp: true }, autoConflicts: [] },
  onLoad(options) { const datasetId = options?.datasetId || wx.getStorageSync('activeDatasetId') || ''; this.setData({ datasetId }); if (!datasetId) { this.setData({ error: '请先导入或选择数据集' }); return; } this.loadBase(); },
  async loadBase() { this.setData({ loading: true, error: '' }); const [classes, students] = await Promise.all([loadTeacherData({ collectionName: 'classes', datasetId: this.data.datasetId }), loadTeacherData({ collectionName: 'students', datasetId: this.data.datasetId })]); if (!classes.ok || !students.ok) return this.setData({ loading: false, error: classes.error || students.error }); const cls = classes.records[0]; if (!cls) return this.setData({ loading: false, classes: [], allStudents: students.records, error: '请先创建班级' }); const rows = classRows(cls); const cols = classCols(cls); const aisleMode = classAisle(cls); const classStudents = students.records.filter((item) => item.classUuid === cls.uuid && item.status !== '离校'); this.setData({ loading: false, classes: classes.records, allStudents: students.records, students: classStudents, classUuid: cls.uuid, rows, cols, aisleMode, classIndex: 0, selected: null }); this.loadSeats(cls.uuid, rows, cols, aisleMode, classStudents); },
  async loadSeats(classUuid = this.data.classUuid, rows = this.data.rows, cols = this.data.cols, aisleMode = this.data.aisleMode, students = this.data.students) { const result = await callBusinessData({ action: 'query', collection: 'seats', datasetId: this.data.datasetId, classUuid }); const resized = resizeGrid(result?.records || [], rows, cols); this.setData({ grid: decorateGrid(resized.grid, students, cols, aisleMode), selected: null, selectedStudentName: '', selectedSeatNote: '', autoConflicts: [], error: result?.ok ? '' : (result?.errors?.[0] || '读取座位失败') }); },
  selectClass(event) { const classIndex = Number(event.detail.value); const cls = this.data.classes[classIndex]; if (!cls) return; const rows = classRows(cls); const cols = classCols(cls); const aisleMode = classAisle(cls); const students = this.data.allStudents.filter((item) => item.classUuid === cls.uuid && item.status !== '离校'); this.setData({ classIndex, classUuid: cls.uuid, rows, cols, aisleMode, students, selected: null, podiumLabel: '讲台', layoutRemark: '' }); this.loadSeats(cls.uuid, rows, cols, aisleMode, students); },
  selectSeat(event) { const selected = Number(event.currentTarget.dataset.index); const seat = this.data.grid[selected]; this.setData({ selected, selectedStudentName: seat?.displayName || '空座', selectedSeatNote: seat?.seatNote || '' }); },
  chooseStudent(event) { if (this.data.selected === null) return; const student = this.data.students[Number(event.detail.value)]; const studentUuid = student?.uuid || ''; if (studentUuid && this.data.grid.some((seat, index) => index !== this.data.selected && seat.studentUuid === studentUuid)) return wx.showToast({ title: '该学生已在座位图中', icon: 'none' }); const grid = cleanGrid(this.data.grid); grid[this.data.selected].studentUuid = studentUuid; this.setData({ grid: decorateGrid(grid, this.data.students, this.data.cols, this.data.aisleMode), selectedStudentName: student?.name || '空座', selectedSeatNote: String(student?.seatNote ?? student?.seat_note ?? '') }); },
  toggleLock() { if (this.data.selected === null) return; const grid = cleanGrid(this.data.grid); grid[this.data.selected].locked = !grid[this.data.selected].locked; this.setData({ grid: decorateGrid(grid, this.data.students, this.data.cols, this.data.aisleMode) }); },
  clearSeat() { if (this.data.selected === null) return; const grid = cleanGrid(this.data.grid); grid[this.data.selected].studentUuid = ''; this.setData({ grid: decorateGrid(grid, this.data.students, this.data.cols, this.data.aisleMode), selectedStudentName: '空座', selectedSeatNote: '' }); },
  onTextInput(event) { this.setData({ [event.currentTarget.dataset.field]: event.detail.value }); },
  onLayoutNumber(event) { const field = event.currentTarget.dataset.field; const value = Number(event.detail.value); if (!['rows', 'cols'].includes(field) || !Number.isInteger(value) || value < 1 || value > 20) return wx.showToast({ title: '行列应为 1 至 20', icon: 'none' }); const rows = field === 'rows' ? value : this.data.rows; const cols = field === 'cols' ? value : this.data.cols; const resized = resizeGrid(cleanGrid(this.data.grid), rows, cols); const apply = () => this.setData({ rows, cols, grid: decorateGrid(resized.grid, this.data.students, cols, this.data.aisleMode), selected: null, autoConflicts: [] }); if (!resized.removed.length) return apply(); wx.showModal({ title: '缩小座位区域', content: `将移除 ${resized.removed.length} 个已占用或锁定座位，是否继续？`, confirmColor: '#d64541', success: (result) => { if (result.confirm) apply(); else this.setData({ [field]: this.data[field] }); } }); },
  onAisleChange(event) { const aisleMode = Number(event.detail.value); this.setData({ aisleMode, grid: decorateGrid(cleanGrid(this.data.grid), this.data.students, this.data.cols, aisleMode) }); },
  toggleAutoOption(event) { const key = event.currentTarget.dataset.key; if (!key) return; this.setData({ [`autoOpts.${key}`]: Boolean(event.detail.value) }); },
  autoArrange() { const result = arrangeStudents({ students: this.data.students, grid: cleanGrid(this.data.grid), rows: this.data.rows, cols: this.data.cols, aisleMode: this.data.aisleMode, options: this.data.autoOpts }); this.setData({ grid: decorateGrid(result.grid, this.data.students, this.data.cols, this.data.aisleMode), autoConflicts: result.conflicts.map((item) => item.message), selected: null }); wx.showToast({ title: result.unplaced.length ? `还有 ${result.unplaced.length} 人未入座` : '自动排座完成', icon: result.unplaced.length ? 'none' : 'success' }); },
  shift(event) { const dr = Number(event.currentTarget.dataset.dr) || 0; const dc = Number(event.currentTarget.dataset.dc) || 0; const movable = cleanGrid(this.data.grid).filter((item) => item.studentUuid && !item.locked); const next = cleanGrid(this.data.grid).map((item) => item.locked ? item : ({ ...item, studentUuid: '' })); for (const item of movable) { const row = (item.row + dr + this.data.rows) % this.data.rows; const col = (item.col + dc + this.data.cols) % this.data.cols; const target = next.find((seat) => seat.row === row && seat.col === col); const fallback = next.find((seat) => !seat.locked && !seat.studentUuid); if (target && !target.locked && !target.studentUuid) target.studentUuid = item.studentUuid; else if (fallback) fallback.studentUuid = item.studentUuid; } this.setData({ grid: decorateGrid(next, this.data.students, this.data.cols, this.data.aisleMode), selected: null }); },
  async showHistory() { const result = await callBusinessData({ action: 'layoutHistory', collection: 'seat_layouts', datasetId: this.data.datasetId, classUuid: this.data.classUuid }); this.setData({ history: result?.records || [], historyVisible: true, error: result?.ok ? '' : (result?.errors?.[0] || '读取历史布局失败') }); },
  restoreHistory(event) { const history = this.data.history[Number(event.currentTarget.dataset.index)]; if (!history?.grid) return; const rows = Number(history.rows) || this.data.rows; const cols = Number(history.cols) || this.data.cols; const aisleMode = [0, 1, 2].includes(Number(history.aisleMode)) ? Number(history.aisleMode) : this.data.aisleMode; const resized = resizeGrid(history.grid, rows, cols); this.setData({ rows, cols, aisleMode, podiumLabel: history.podiumLabel || '讲台', layoutRemark: history.remark || '', autoOpts: { ...this.data.autoOpts, ...(history.autoOpts || {}) }, grid: decorateGrid(resized.grid, this.data.students, cols, aisleMode), selected: null, historyVisible: false }); wx.showToast({ title: '已载入历史布局', icon: 'success' }); },
  async save() { const cls = this.data.classes.find((item) => item.uuid === this.data.classUuid); if (!cls) return wx.showToast({ title: '请先选择班级', icon: 'none' }); this.setData({ saving: true, error: '' }); const classResult = await callClassData({ action: 'update', datasetId: this.data.datasetId, uuid: this.data.classUuid, class: { ...cls, seatRows: this.data.rows, seatCols: this.data.cols, aisleMode: this.data.aisleMode } }); if (!classResult?.ok) return this.setData({ saving: false, error: classResult?.errors?.[0] || '座位参数保存失败' }); const existing = await callBusinessData({ action: 'query', collection: 'seats', datasetId: this.data.datasetId, classUuid: this.data.classUuid }); if (!existing?.ok) return this.setData({ saving: false, error: existing?.errors?.[0] || '读取原座位失败' }); for (const item of existing.records || []) { const removed = await callBusinessData({ action: 'delete', collection: 'seats', datasetId: this.data.datasetId, classUuid: this.data.classUuid, uuid: item.uuid }); if (!removed?.ok) return this.setData({ saving: false, error: removed?.errors?.[0] || '清理原座位失败' }); } let count = 0; for (const item of cleanGrid(this.data.grid)) if (item.studentUuid || item.locked) { const result = await callBusinessData({ action: 'create', collection: 'seats', datasetId: this.data.datasetId, classUuid: this.data.classUuid, record: item }); if (!result?.ok) return this.setData({ saving: false, error: result?.errors?.[0] || '座位保存失败' }); count += 1; } const snapshot = await callBusinessData({ action: 'layoutSave', collection: 'seat_layouts', datasetId: this.data.datasetId, classUuid: this.data.classUuid, layout: { rows: this.data.rows, cols: this.data.cols, aisleMode: this.data.aisleMode, podiumLabel: this.data.podiumLabel, remark: this.data.layoutRemark, autoOpts: this.data.autoOpts, grid: cleanGrid(this.data.grid) } }); this.setData({ saving: false, error: snapshot?.ok ? '' : (snapshot?.errors?.[0] || '布局历史保存失败') }); if (!snapshot?.ok) return; wx.showToast({ title: `已保存 ${count} 个座位`, icon: 'success' }); this.loadSeats(); },
});
